require('custom.plugins.yank')
require('custom.plugins.telescope')
require('custom.plugins.nvimr')
require('custom.plugins.treesitter')
require('custom.plugins.lsp')
-- require('custom.plugins.cmp')
require('custom.plugins.harpoon')
require('custom.plugins.undotree')
require('custom.plugins.fugitive')

